language: php
php:
  #- 7.1
- 7.2
- 7.3
- nightly

addons:
  postgresql: '9.6'
  code_climate:
    repo_token: "$CODECLIMATE_API_TOKEN"
services:
- postgresql
- redis-server
cache:
  directories:
  - node_modules
  - "~/.composer/cache"
sudo: false
dist: trusty
notifications:
  slack:
    secure: g5gScU7zKCyMI1gZnoezl4VDAFQ5DZgr/Vav5kVbxCiItw+J6vvMqygmK5CFwNaYwvStJ9tIfJPvbxlRyEfF3qzRyCtpzKelbzyG79y/ecICVFI3Qd52FyXmgk/HrijxqeBU3geSSu1yi9fObf6DpmJ9jBdAeyCJ1dXCaaPe75aq7tPljxd4Qh2Omw/XjTdTqO5YWZ1wM3CAuIrobDtDNQ+fDHpam5Kdb62T9uR0d7MTHygHefoOw+1AWHVggNzAP4uBi7rU3XXMJDeAjUlPw6Mg3SRhsfJ3RechLVq/7dw7fQpHsoG8o6ySqd6CvLT2qFFdQ6kX3nSMIsO49CV8QtghICTwnzqbyhnQeI05tqlkYDC0i9AY4TF7kx4Uy7GvrvjjekJlMBGNLrYzPoSYBIms1lGbprqDAASoM73m4IhNWQ0GQiMeIf1ctrgzj0H0SxPPGSANn57YIAfhsioXsR/ChvNhreUyNHBinAO3afR7VI0utsPLwWiKzvDDh7NzIwqFzgQAeocu3pbuStPk1/hQZiMjJINNlFPHv/00j36+YuqKJxPM1y+fis1cloEsHhx29tKy9RtqyHlXsszTM34gbmQuSzJ+oLaaKm63uCAAPJFgb1g01/57ZlIbnZ9riGIORMkoJvqbDO7MRllpGFvSVjewSy6XroC5wjlGSZ4=
install:
  - composer install
  - composer require codedungeon/phpunit-result-printer
before_script:
- psql -c 'create database giveblood_test;' -U postgres
#- composer require codeclimate/php-test-reporter --dev
script:
- php artisan migrate --env=testing --no-interaction
- ./vendor/bin/phpunit
- sh ./cache-clean.sh
after_success:
- bash <(curl -s https://codecov.io/bash)
#- vendor/bin/test-reporter
