# v2 sintax
version: '2'

# Named volumes
volumes:
  # MySQL Data
#  giveblood-mysql-data:
#    driver: local

  # postgresql
  giveblood-pgsql-data:
    driver: local

  # Redis Data
  giveblood-redis-data:
    driver: local

services:
  # MySQL (5.7)
#  mysql:
#    image: mysql:5.7
#    container_name: giveblood-mysql
#    volumes:
#      - giveblood-mysql-data:/var/lib/mysql
#    ports:
#      - "3306:3306"
#    environment:
#      - MYSQL_ROOT_PASSWORD=giveblood
#      - MYSQL_DATABASE=giveblood
#      - MYSQL_USER=giveblood
#      - MYSQL_PASSWORD=giveblood

  # Postresql (Alpine)
  postgres:
    image: postgres:alpine
    container_name: giveblood-pgsql
    volumes:
      - giveblood-pgsql-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=giveblood
      - POSTGRES_USER=giveblood
      - POSTGRES_PASSWORD=giveblood

  # Redis
  cache:
    image: ambientum/redis:3.2
    container_name: giveblood-redis
    command: --appendonly yes
    volumes:
      - giveblood-redis-data:/data
    ports:
      - "6379:6379"

  # APP (with Caddy)
  app:
    image: ambientum/php:7.0-caddy
    container_name: giveblood-app
    volumes:
      - .:/var/www/app
    ports:
      - "80:8080"
    links:
      - postgres
      - cache

  # Laravel Queues
  queue:
    image: ambientum/php:7.0
    container_name: giveblood-queue
    command: php artisan queue:listen
    volumes:
      - .:/var/www/app
    links:
      - postgres
      - cache
